### ISSUE TITLE
once i provide information in "Report" from the top-right menu of an exercise card, I should be automatically moved to the next exercise!

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Exercises-Platform#110]
it has happened to me multiple times that i provide this feedback, and then i'm disappointed that i still have to click "next" on my own, when it is clear that this is the only thing i would even want to do anyway :)

**Comment by sibrenvanvliet** [comment]
Does it suffice here to simply automatically call the same method that would be triggered by clicking the 'check' button? This would mean that all data, such as the given answer and the number of hints used, is sent to the server as usual.

**Comment by mircealungu** [comment]
in principle yes. even if the given answer will not be very relevant, and might not be given at all.

**Comment by mircealungu** [comment]
I have to look at the code, but I think that the method is already called, since the information is uploaded to the server. However, in the method that's called in the Check button's event there must be something else that advances the exercise. 

Also, this is related to: issue #116
