### ISSUE TITLE
if there are no words to study maybe simply let the user go to their original intent

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Exercises-Platform#111]
now i get intercepted and i'm invited to read... but ti's the wrong time to go reading. i could do an exercise or two, but reading... meh.

<img width="1434" alt="screenshot 2017-08-18 15 20 33" src="https://user-images.githubusercontent.com/464519/29460605-e0ed9a24-8428-11e7-91f2-b7dd16ab00ca.png">

**Comment by martinavagyan** [comment]
Interesting, I took care of this scenario as it can be seen from the picture below: 

![image](https://user-images.githubusercontent.com/7386708/29463966-b8474bd6-8434-11e7-953a-dfec942eabdf.png)
I think the problem might be from the url. I will try to fix it from TDS side.

**Comment by martinavagyan** [comment]
Actually, even with the current version, it shows this option to me:
![image](https://user-images.githubusercontent.com/7386708/29464345-e38caeb6-8435-11e7-93be-c47f438d5ca2.png)

**Comment by mircealungu** [comment]
strange!
maybe i was not starting from the interceptor but
from the exercises link from zeeguu?

**Comment by martinavagyan** [comment]
The exercises check if the URL contains interceptor redirect. If it does the skip button is presented.
