### ISSUE TITLE
hint should reveal one letter at a time

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Exercises-Platform#112]
can we do this? it would be much cooler than revealing the answer completely i think.

**Comment by mircealungu** [comment]
this actually, makes sense to only one type of exercise: the one where the answer is not in the text.

**Comment by mircealungu** [comment]
actually, there are two types of exercises who have free text input; would it make sense to have the letter-by-letter hint revealing for both of them?

**Comment by mircealungu** [comment]
The "Find the word in context" type of exercise also simply dumps the solution on hint. Again, adding letter by letter should be preferred.

**Comment by sibrenvanvliet** [comment]
Good idea, will do! In the other exercise types, asking for a hint causes an option to be crossed out. This should remain the same? Personally I think that this is a nice way to handle hints with these multiple choice questions.

**Comment by mircealungu** [comment]
The crossing out of choices is indeed a good approach to handling hints in multiple choice exercises. It should stay indeed!

**Comment by sibrenvanvliet** [comment]
Now that I am working on fixing the pull request, I had another idea. Currently, the hint for a phrase like "il fait" looks like "i......". Would it be better to write "i. ....", to show that there are two words? Another case: should the first hint for "avez-vous" appear as "a........" or "a...-...."?

**Comment by mircealungu** [comment]
Eheh. I like how you think :)
Definitely the spaces are useful!
other punctuation... might be too helpful maybe?
I let you decide !

**Comment by sibrenvanvliet** [comment]
I will stick to spaces for now, and implement it in a way that other punctuation cases can be easily added later :)
