### ISSUE TITLE
Once there's text in the exercise input box: hints don't work anymore

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Exercises-Platform#122]
To think about: if I input text, the hint does not work anymore. 

happened to me that I introduced what I thought was the right answer, but the system was expecting another answer. Now next does not work because the answer is wrong. And the hint does not work because the placeholder is not visible when there's text inside

**Comment by sibrenvanvliet** [comment]
Good point, that is a drawback of using the placeholder attribute. An idea is to clear the input text in the textbox when the hint button is clicked. Then the hint becomes visible, but a possible drawback is that the user loses the text they typed in.

**Comment by mircealungu** [comment]
yes, it's an idea... i think we'd have to see it in action to understand whether it works or is frustrating... but intuition tells me that it will work :)

**Comment by sibrenvanvliet** [comment]
This bug is resolved since the latest pull request.
