### ISSUE TITLE
Show which words were matched in Ex3

### ISSUE THREAD

**Issue by sibrenvanvliet** [zeeguu-ecosystem/Exercises-Platform#124]
While working on #97, I noticed that it is difficult for a learner to review their answer in the 'match each word with its translation' exercise. If the user does not remember which word they matched with which translation, they cannot review their input. For example, in this solved exercise, you cannot tell from the screenshot which word matches with which translation:
![match](https://user-images.githubusercontent.com/17131312/34576310-c6366d88-f17d-11e7-82bd-cd82c2b7b0aa.png)

I am wondering if this is an issue. If it is, there are several ways to solve it. One could be to draw lines between two phrases as soon as they are correctly matched:
![match2](https://user-images.githubusercontent.com/17131312/34576570-9646aeca-f17e-11e7-9ff4-bc1ab410f461.png)

Another possibility is to print the words and translations next to each other after success, for example:
![match3](https://user-images.githubusercontent.com/17131312/34576816-72992722-f17f-11e7-9f4d-5823b3091145.png)

**Comment by mircealungu** [comment]
Nice observation Sibren!

It would be indeed nice to have the solution
remain on the screen for a bit.

Probably the simplest solution is the last?

Oh, I think I have an even simpler one!

What about highlighting the pairs with different
colors (shades of green)?

No more playing with layouts!

[image: Inline image 1]

**Comment by mircealungu** [comment]
Also, you could add "semantics" to the colors:
- first match would be the darkest green, since it's the one
the learner knows the best.
- second would be lighter
- third would be very light... they clearly didn't "know" it as
they knew the other two :)

**Comment by sibrenvanvliet** [comment]
I think that's an elegant and thoughtful solution! Then I will do it like that :)
