### ISSUE TITLE
make sure that in fill-in-the-blanks number of words does not give away 't solution 

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Exercises-Platform#132]
When I do an exercise with two lines to fill in, there are options to fill in just one word. That makes it really easy to choose the correct one so it doesn't really help for vocabulary skills.

**Comment by sibrenvanvliet** [comment]
This indeed makes it easy to 'cheat' and get past an exercise without even thinking about the words on screen, so a problem in vocabulary skill training.

The easiest solution would be to show only a single 'blank' line in the context on screen, not one for each word. This way, the learner must figure out if one word or multiple words are the solution.

A different approach is showing multiple 'blank' lines on screen, and offering only choices with the same number of words. However, this will make it more difficult to pick random choices from the batch of the learner's vocabulary. And if a certain phrase consists of, say, four words, the chance is small that a learner even has two other phrases of four words in their vocabulary.

**Comment by mircealungu** [comment]
I only thought about the second idea.
But I like the first. It's a quick fix and is just as good!

**Comment by sibrenvanvliet** [comment]
I will do that then! :)
