### ISSUE TITLE
asymmetric layout is a bit strange...

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Exercises-Platform#58]
<img width="854" alt="screenshot 2017-05-31 10 11 29" src="https://cloud.githubusercontent.com/assets/464519/26622118/9ded2adc-45e9-11e7-8fa1-6e313c07165b.png">

personally i would have preferred to see the options buttons centered

**Comment by martinavagyan** [comment]
@mircealungu, in the beginning, it was strange for me as well, but I got used to the design, do you still consider it strange?

**Comment by mircealungu** [comment]
Yes :)
We need an arbiter :)

**Comment by martinavagyan** [comment]
This is the case to do A/B testing :)

**Comment by sibrenvanvliet** [comment]
In other exercise types, there is a green 'check' button on the right side, causing the answer choices to be nicely centered. We could put an empty container on the right side, so without the green button (because clicking an answer choice already submits it).

![](https://i.imgur.com/WUbvE1A.png)

However, this reduces the room for the answer choice buttons by a lot. Currently the buttons have a maximum width and a maximum of two lines, like this:

![](https://i.imgur.com/GBHvFU7.png)

So if the text in the three choice buttons is long (and languages like Dutch and German can have very long words), the answers cannot be shown completely. What should be done in this case? Possible solutions:
1. Putting the answer choice buttons on separate lines. However, this would really change the design of the page on some questions.
2. Make the containers on the left (with the hint button) and right narrower.
3. Disable the empty right container in this case (putting us back at square one).
4. Other ideas?

**Comment by mircealungu** [comment]
that's a good point. if we want to maximize the space
at the bottom we can: 

1. move the hint button from where it is now to the place
where now we have the "pronounce" button... 
especially since most of the times that button does not 
make sense as it gives away the answer!! 

in fact, the hint button could almost always replace 
what's now "pronounce"... since that button would only
make sense to appear when the solution is revealed 
and at that time, the hint is not needed. 

2. make the hint button smaller, and move it more to 
the left margin, such that it leaves much more space
for the solution options.

**Comment by sibrenvanvliet** [comment]
My choice would be to replace the speaker button with the hint button. Indeed, it is nice for the user to listen to the word, **after** they saw that it was correct. So the hint button only needs to exist before the answer is revealed, and the speaker button only needs to exist after the answer is revealed.

The result is that the entire width of the grey bar at the bottom of the screen, can be used for displaying the multiple choice buttons.

**Comment by mircealungu** [comment]
agreed! this is the best approach!

**Comment by sibrenvanvliet** [comment]
Right now I'm toying a bit with moving the hint button. For Ex2, it indeed looks nice to have the buttons aligned in the centre. But it takes some getting used to the new location for the hint button ;)
![058b](https://user-images.githubusercontent.com/17131312/34617553-1e51ef92-f23c-11e7-8601-eabb862b13b8.png)

For a text input exercise, the bottom bar now looks a bit unbalanced... But this may look less jarring when the question mark button gets a bit of a redesign, making it smaller and the colour less contrasting.
![058a](https://user-images.githubusercontent.com/17131312/34617631-5fa4d982-f23c-11e7-9cdc-8680a2f30360.png)

Moving the hint button somehow causes a bug in Ex3 where one word too many gets disabled, making it impossible to pass the exercise.
![058c](https://user-images.githubusercontent.com/17131312/34617660-7991cef4-f23c-11e7-81a6-64d291534edf.png)

**Comment by mircealungu** [comment]
Whoa! 
Bug in Ex3 when you move the hint in Ex 2? 
That's bad...

And you know what? 
Why don't we simply remove the hint button in Ex2
and be done with it? 

Arguments pro:
- fast
- there's already a nice animation when you click on 
the wrong answer, so that's already a hint!! 

yeah, it's a pitty for the animation that

**Comment by sibrenvanvliet** [comment]
Indeed, maybe a hint is not actually necessary in Ex2. In an exercise where you have to type text, you would be stuck if you cannot come up with the answer, so the hint button is important there. But in Ex2, you can always just guess and randomly select one option if you don't know the answer, so you are never stuck.

**Comment by mircealungu** [comment]
Exactly.
I had the same idea. Hints are critical for text exercises!

On Jan 6, 2018 6:00 PM, "sibrenvanvliet" <notifications@github.com> wrote:

Indeed, maybe a hint is not actually necessary in Ex2. In an exercise where
you have to type text, you would be stuck if you cannot come up with the
answer, so the hint button is important there. But in Ex2, you can always
just guess and randomly select one option if you don't know the answer, so
you are never stuck.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/zeeguu-ecosystem/Exercises-Platform/issues/58#issuecomment-355756074>,
or mute the thread

**Comment by sibrenvanvliet** [comment]
Okay, then I will simply remove the hint button and functionality from Ex2 :)

**Comment by mircealungu** [comment]
+1
