### ISSUE TITLE
got it right, but still don't know what it means :)

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Exercises-Platform#97]
it would be good to show also the translation in such a case!

<img width="911" alt="screen shot 2017-06-21 at 12 17 20" src="https://user-images.githubusercontent.com/464519/27379470-a2d337d8-567b-11e7-9a3d-d9d78a1055b5.png">

**Comment by leverworst** [comment]
I think that simply printing the translation in the centre of the green bar would be sufficient here.

![](https://i.imgur.com/nqrEyDI.png)

**Comment by sibrenvanvliet** [comment]
(Wrong account ;) )
I think that simply showing the translation in the centre of the green bar would be sufficient.

![](https://i.imgur.com/nqrEyDI.png)

**Comment by mircealungu** [comment]
Looks nice. 
But another thing that can be done is to 
take advantage of the fact that the instruction
message (e.g. "Choose the word...") does not
make sense anymore to be displayed  on the 
screen). Thus, we could hide that one, and
use the space to say something like: 

"Correct! In this context, angeven zich = report"

**Comment by mircealungu** [comment]
Another situation that is similar is for this other type of exercise: 

![screenshot 2017-12-09 17 07 20](https://user-images.githubusercontent.com/464519/33797164-7cf7dfb4-dd03-11e7-99e7-938ffa8fe089.png)

**Comment by mircealungu** [comment]
At this point, the "find the word..." does not make sense anymore.

**Comment by sibrenvanvliet** [comment]
Replacing the question prompt with the answer is a great idea for having as little clutter on the screen as possible.

But a question is, if the user is curious to see the translation of a word, where would they expect to find it? Where the question was, or where the green bar popped up? Personally, I would think that the user expects the green bar to give the answer, but I can't know for sure.

**Comment by mircealungu** [comment]
Good point! 
The green thing appears and attracts the attention of the user. 

However, the green thing, is relevant at the meta-level: it is 
**about** the exercise: it allows moving to the next exercise, or 
providing feedback on the current one. Putting the word *in* 
there would make sense if the word would be a button. 

One thing that can be done is to play a bit bolder with the colors
so the attention of the learner is still in the upper part of the 
screen. Something like this maybe? 

![screenshot 2017-12-09 17 43 38](https://user-images.githubusercontent.com/464519/33797458-8de82720-dd08-11e7-8f5d-693e1e4001d4.png)

and yet another solution, would be to insert the translation right 
there, near the word. e.g.: 

![screenshot 2017-12-09 17 46 57](https://user-images.githubusercontent.com/464519/33797488-014e3812-dd09-11e7-8490-646db730dde3.png)

**Comment by mircealungu** [comment]
for the second example I provided, the challenge / solution could be rendered like this. 

![screenshot 2017-12-09 17 53 15](https://user-images.githubusercontent.com/464519/33797576-def5715c-dd0a-11e7-8c42-f064fa993aa7.png)

![screenshot 2017-12-09 17 58 15](https://user-images.githubusercontent.com/464519/33797579-eeba1548-dd0a-11e7-8c21-0b682f90f6fe.png)

**Comment by sibrenvanvliet** [comment]
What about writing the instruction between the speaker button and the menu button? We are not using that whitespace, are we? Personally I think it looks better than having it stick out of the white container.

**Comment by mircealungu** [comment]
good idea! 
we must probably make the font a bit smaller, or reduce the text to something shorter, in order to make it fit also on the mobile. see: 

![screenshot_20171211-111319](https://user-images.githubusercontent.com/464519/33826516-89e99b32-de65-11e7-934f-f284980e81ba.png)

This is how it would look. 

![screenshot 2017-12-11 11 28 12](https://user-images.githubusercontent.com/464519/33826813-6fc23a4c-de66-11e7-9382-d4733db530ab.png)

Not bad. Maybe it looks a bit unbalanced now with the green button the only thing standing out of the form. If we switch that to gray though, it would not be bad actually. e.g. 

![screenshot 2017-12-11 11 27 55](https://user-images.githubusercontent.com/464519/33826862-a005032e-de66-11e7-81c0-e6ae0aadde5b.png)

**Comment by mircealungu** [comment]
Cool idea. It would look good actually. 
Also, we must make sure that the font is a bit smaller on the phone, as you can see, currently it's a bit too large. 

![screenshot 2017-12-11 11 35 57](https://user-images.githubusercontent.com/464519/33827144-8e6bcbe2-de67-11e7-9245-69aa97a79615.png)

**Comment by sibrenvanvliet** [comment]
Good that you mention it, I will be keeping an eye on how it looks on mobile :)

**Comment by sibrenvanvliet** [comment]
I have moved the exercise prompt to the top bar, which is also used for the success animation. So when the question is answered correctly, the exercise prompt disappears to make room for the success animation. This way, when the user has answered the question, they can review the word and its translation, without the prompt causing unnecessary clutter.

When on mobile, the question prompt takes up two lines of text. The result is that when the prompt is removed and replaced by the animation, the on-screen text moves around, which is distracting.
![097a](https://user-images.githubusercontent.com/17131312/34573872-e7ac82de-f175-11e7-9a7c-14b85d658e9a.png)

You suggested earlier to use a smaller font on mobile. But I think that the prompt would then become too small to read. My idea is to give the header a fixed height on mobile, such that the text fits on two lines and the header does not automatically resize when the prompt is hidden. Would you agree?

**Comment by mircealungu** [comment]
You could make it as large as the font in the address bar it should be ok. And that's a font everybody should be able to see! Also, it's something you don't always have to read. Only the first time really.

<img width="280" alt="screenshot 2018-01-06 18 37 53" src="https://user-images.githubusercontent.com/464519/34641708-efe07504-f310-11e7-90ab-20cc9af72f3d.png">

**Comment by sibrenvanvliet** [comment]
True, but some instructions are longer than that one, so then it would go to two lines again. The version that was just merged has the text in a bigger font and its container a fixed height. How do you like how that looks?
